name: eeg_analyzer_frontend
description: Flutter Web EEG signal analysis MVP.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3
  file_picker: ^8.0.3
  fl_chart: ^0.68.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
